#Dummy Configuration of Decay Vessel for FairShip (Naples Design)

sensitiveThickness: 0.01  # cm
sensitiveMed: "vacuum"
decayMed: "helium"

xstartInner : 100.0 # cm
ystartInner : 270.0 # cm
xendInner : 400.0 # cm
yendInner : 600.0 # cm
z0: -2478.0 # cm Decay Vessel Start
