# Configuration of Decay Vessel for FairShip (Naples Design)

z: 0.0
innerSupport: 0.8 # cm
innerSupportMed: "vacuum"
outerSupport: 0.8 # cm
outerSupportMed: "vacuum"
lidThickness: 0.0  # cm
<<<<<<< HEAD
sensitiveThickness: 20  # cm
=======
sensitiveThickness: 0.1  # cm
>>>>>>> 72ecbf89 (Changing UBT to a dummy counting plane and adding last bit of muon shield with Stellatryon v2 dimensions and remove veto system (Work in Progress))
sensitiveMed: "vacuum"
decayMed: "helium"
rib: 1.5  # cm
ribMed: "vacuum"
xstartInner : 100.0 # cm
ystartInner : 270.0 # cm
xendInner : 400.0 # cm        #FocusLineX at z= target.z0 + 16.8m
yendInner : 600.0 # cm        #FocusLineY at z= target.z0 - 7.4m
z0: -2478.0 # cm   Decay Vessel Start
